[package]
name = "telegraph"
version = "0.0.1"
edition = "2021"
authors = ["Filipponik"]
description = "Telegra.ph API"
readme = "README.md"
repository = "https://github.com/Filipponik/telegraph"
keywords = ["axum-rs", "server", "web-server", "telegram", "telegraph"]
categories = ["web-programming", "web-programming::http-server", "command-line-interface", "api-bindings"]

[profile.release]
strip = true
opt-level = "s"
lto = true
codegen-units = 1
panic = "abort"

[dependencies]
reqwest = { version = "0.12.5", features = ["json"] }
tokio = { version = "1.32.0", features = ["full"] }
serde = { version = "1.0.204", features = ["derive"] }
serde_json = "1.0"
dotenv = "0.15.0"
headless_chrome = {git = "https://github.com/rust-headless-chrome/rust-headless-chrome", features = ["fetch"]}
futures = "0.3.30"